services:
  app:
     image: sammy43/patienthub:0.0.1
     ports:
        - 8080:8080
     environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/patienthub?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: root
     depends_on:
        - db
        
  db:
     image: mysql:8.0
     environment:
        DATABASE_HOST: docker-mysql
        DATABASE_PORT: 3306
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABSE: patienthub
        MYSQL_USER: admin
        MYSQL_PASSWORD: root
        
        
       
     
  